### PR TITLE
Add support for Belgian Cappacity Tarif regarding eMUCs – P1 V1.7.1

### PR DESCRIPTION
**Pull request by mhostyn**
Following The documentation at [maakjemeterslim.be](https://maakjemeterslim.be/aanbieder)  (e-MUCS_P1_Ed_1_7_1.pdf)  i added and tested the addition of the folowing codes:
 - Current average demand - Active energy import, (1-0:1.4.0)
 - Maximum demand – Active energy import of the running month, (1-0:1.6.0)
 
 I did not add:
  - Maximum demand – Active energy import of the last 13 months, (0-0:98.1.0)
  
 As it seems to be a tripple timestamp+value (man,max,avg?) string and am unable to find if this can be parsed at this point.
 Example (0-0:98.1.0(3)(1-0:1.6.0)(1-0:1.6.0)(200501000000S)(200423192538S)(03.695*kW)(200401000000S)(200305122139S)05.980*kW)(200301000000S)(200210035421W)(04.318*kW))

### CODE REVIEW

**Comment by glmnet** [comment]
Did you test this on your hardware already?

**Comment by mhostyn** [comment]
Yes, i am using this code at the moment and am receiving the values as expected

image

**Comment by mhostyn** [comment]
Please excuse me, but when trying to test end recompiling it seems something went wrong, so i`ll have to hold for now and find out where i went wrong, sorry should have tested after renaming the fields

**Comment by mhostyn** [comment]
Found and fixed the error, at some point changed the Timestamp to FixedValue
Sorry for the inconvenience -.-'

and here is a new chart with the up-to-date code
image

**Comment by glmnet** [comment]
So you're 100% confident now?

**Comment by mhostyn** [comment]
I am yes, i removed all local files, downloaded the latest and did a clean build

lesson learned!

**Comment by deepeebee** [comment]
Please, I was also looking into this as well. What is the current status?
I know it has been merged, but it doesn't show up yet. ESPHome is not yet taking this version to deploy on the ESP.
It would make sense to deploy this, as it is used in BE for electrical billing purposes.
Would be really interesting if we are able to follow up and use it for automations in Home Assistant!
Let me now what is needed, happy to help!

**Comment by michaelarnauts** [comment]
It still needs a change in ESPhome. I think this is the merge request to follow: https://github.com/esphome/esphome/pull/4412

But it seems that this also depends on https://github.com/glmnet/arduino-dsmr/pull/15, so I'm not really sure where we are on getting this functionality.

**Pull request merged**
